### ISSUE TITLE
Metasploit

### ISSUE THREAD

**Issue by shelld3v** [wdahlenburg/CVESearch#4]
Search for CVE exploit modules (Metasploit): https://www.rapid7.com/db/?q=CVE&type=metasploit

**Comment by wdahlenburg** [comment]
I opted to implement this by directly searching the [metasploit-framework repo](https://github.com/rapid7/metasploit-framework/) in c0d4573. Let me know if you see any differences in searching.

Metasploit modules use a syntax like `[ 'CVE', '2020-2555' ]`, which is a bit of a challenge to catch with just the Github Search API due to spacing/line breaks. This commit will just search for '2020-2555' and ensure the path is in the `modules/exploits/` folder.
