### ISSUE TITLE
Able to search for resources only

### ISSUE THREAD

**Issue by shelld3v** [wdahlenburg/CVESearch#5]
Sometimes exploits (or even just description, demo, ...) are mentioned in the write-ups. Therefore, there should be an option to search for all resources about the CVE, extract links from sources like [CVE Details](https://www.cvedetails.com/), [Mitre](https://cve.mitre.org/), ...

**Comment by wdahlenburg** [comment]
I'd be okay adding an optional flag to search some datasources for a CVE description. That description could be prefixed to the tool's output. Would this work?

I'm not looking to add all links to resources because this tool is intended to provide reliable searches for proof-of-concepts. There are a LOT of resources that talk about CVEs, but that information is mostly noise when trying to determine if a CVE has a real proof-of-concept. Site owners need to have someone manually confirm if a url (blog, code, video, etc) is a proof-of-concept or if it's just generic CVE details.

**Comment by shelld3v** [comment]
> I'd be okay adding an optional flag to search some datasources for a CVE description. That description could be prefixed to the tool's output. Would this work?

👍 

> I'm not looking to add all links to resources because this tool is intended to provide reliable searches for proof-of-concepts. There are a LOT of resources that talk about CVEs, but that information is mostly noise when trying to determine if a CVE has a real proof-of-concept. Site owners need to have someone manually confirm if a url (blog, code, video, etc) is a proof-of-concept or if it's just generic CVE details.

But it's ok to list all of them and let users choose resources to check by themself (they can visit links that they believe are blog posts and ignore others). Searching for resources on Google is a messy task, cause there are tons of different resources, and each resource has many links to other resources, so it will be very cool if there is a command-line tool that can collect all of them and list everything. Of course, this is an "optional" option

**Comment by wdahlenburg** [comment]
b68cdee added support for a `-description` flag, which grabs the CVE description from either NIST or Mitre. The description is the extent of CVE information I'm looking to provide, because this tool is intended to only provide references to proof-of-concepts for CVEs.

A custom version could be created to grab links for all urls from a datasource, however I'm not looking to go in that direction with this project.

I find it exhausting to manually visit every related link when researching a CVE. This project will definitely miss some blog posts as a result of not returning all urls. The tradeoff is that I have better confidence that a POC is valid and less urls to sort through. Datasources can always be added if they are consistent/reliable.

**Comment by justforhack** [comment]
If we only print out the description, then should we enable it by default?

>I find it exhausting to manually visit every related link when researching a CVE.

For me, not really, it would worth my time if I found a real good one. Special, people with experience can filter uninteresting links by themself, such as www.redhat.com, www.tenable.com, www.debian.org, www.oracle.com, ... Or even we can implement a filter for cvesearch

>This project will definitely miss some blog posts as a result of not returning all URLs

We just need as many datasources as possible

**Comment by shelld3v** [comment]
If we only print out the description, then should we enable it by default?

>I find it exhausting to manually visit every related link when researching a CVE.

For me, not really, it would worth my time if I found a real good one. Special, people with experience can filter uninteresting links by themself, such as www.redhat.com, www.tenable.com, www.debian.org, www.oracle.com, ... Or even we can implement a filter for cvesearch

>This project will definitely miss some blog posts as a result of not returning all URLs

We just need as many datasources as possible

(Sorry I just used my garbage account to comment:)

**Comment by shelld3v** [comment]
It's ok if you don't want to work on this, I might create a project for it

**Comment by wdahlenburg** [comment]
> It's ok if you don't want to work on this, I might create a project for it

Yeah that's fine. I'm looking to keep this project to just POCs. You are definitely welcome to do a hard fork of it. If you identify any POC datasources, send them my way
